name: Build and Push to ACR

on:
  push:
    branches:
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      REGISTRY: sdav2.azurecr.io
      IMAGE_IAM: lme

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Podman
        run: |
          sudo mkdir -p /etc/apt/keyrings
          curl -fsSL https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/xUbuntu_22.04/Release.key \
            | gpg --dearmor | sudo tee /etc/apt/keyrings/libcontainers-archive-keyring.gpg > /dev/null

          echo "deb [signed-by=/etc/apt/keyrings/libcontainers-archive-keyring.gpg] \
          https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_22.04/ /" \
          | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list

          sudo apt-get update
          sudo apt-get install -y podman

      - name: Debug Info
        run: |
          uname -a
          podman --version

      - name: Log in to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push LME image
        run: |
          IMAGE_TAG=$(echo "$GITHUB_SHA" | cut -c1-7)
          CUSTOM_TAG=beta_v2
          
          podman build -t $REGISTRY/$IMAGE_IAM:$IMAGE_TAG -t $REGISTRY/$IMAGE_IAM:$CUSTOM_TAG .
          podman push $REGISTRY/$IMAGE_IAM:$IMAGE_TAG
          podman push $REGISTRY/$IMAGE_IAM:$CUSTOM_TAG
