name: Build and Push SDA Backend Images

on:
  push:
    branches:
      - release
  pull_request:
    branches:
      - release

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: |
          pwd
          ls -la

      - run: |
          find . -maxdepth 4 -type d

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: mfsdaplusregistry.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - uses: docker/build-push-action@v5
        with:
          context: ./sda_svc/identity_access_management
          push: true
          tags: |
            mfsdaplusregistry.azurecr.io/sda/iam:latest
            mfsdaplusregistry.azurecr.io/sda/iam:${{ github.sha }}

      - uses: docker/build-push-action@v5
        with:
          context: ./sda_svc/learning_management_engine
          push: true
          tags: |
            mfsdaplusregistry.azurecr.io/sda/lme:latest
            mfsdaplusregistry.azurecr.io/sda/lme:${{ github.sha }}

      - uses: docker/build-push-action@v5
        with:
          context: ./sda_svc/events_and_notifications_system
          push: true
          tags: |
            mfsdaplusregistry.azurecr.io/sda/events:latest
            mfsdaplusregistry.azurecr.io/sda/events:${{ github.sha }}
